apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: forum-alura
  name: forum-alura
spec:
  replicas: 1
  selector:
    matchLabels:
      app: forum-alura
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: forum-alura
    spec:
      containers:
      - image: gcr.io/sacred-archway-208420/forum-alura
        name: forum-alura
        ports:
        - containerPort: 3000
        resources: {}
status: {}